# Etapa 1: Build com Maven
FROM eclipse-temurin:21-jdk-jammy AS builder

WORKDIR /app

COPY .mvn .mvn
COPY mvnw pom.xml ./

RUN ./mvnw dependency:go-offline -B

COPY src ./src

RUN ./mvnw clean package -DskipTests -B

# Etapa 2: Imagem final mais leve
FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

ENV JAVA_OPTS="-Xms256m -Xmx512m"

# Copia apenas o .jar gerado
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
